### PR TITLE
Move all README API sections to an API document

### PR DESCRIPTION
**Pull request by RichardLitt**
### What was wrong

The README is hard to read. However, rather than moving all of the documents to ReadTheDocs, as suggested in #122, you could also just add an API file like so. I think this keeps the documentation closer to the code. A Table of Contents makes it easier to read, so I added that. 

### How I changed it

I've added an API file and moved all of the API docs over, as well as adding a contribute and a license section to the README. For both, I've added a ToC. 

### This PR's mascot

Cute animal picture

### CODE REVIEW

**Comment by pipermerriam** [comment]
The sphinx migration is part of a broader effort so that we can start cross-linking between docs, so unfortunately, basic conversion to sphinx/rtd based docs is a must for this.

**Comment by RichardLitt** [comment]
Cool. Can you point me to where that broader effort is happening? I'd like to read up on it. 

Want me to edit this PR to include the other changes, and just remove the API file and point to ReadTheDocs?

**Comment by njgheorghita** [comment]
@pipermerriam @RichardLitt I have a conversion to RTD/Sphinx ready to go in #111 , it could definitely use a proof-read but AFAIK the docs are up-to-date

**Comment by pipermerriam** [comment]
@njgheorghita it looks as though the webhook is correctly installed and was triggered today.

https://eth-utils.readthedocs.io/en/latest/

That was built today sometime.

**Comment by carver** [comment]
Thanks for the initiative @RichardLitt -- since we have the docs on RTD, I'll close this as resolved elsewhere. If you see something else that you'd like to improve, we would love more contributions from you. Feel free to check in first if you'd like to make sure there isn't duplicate work happening.

**Comment by RichardLitt** [comment]
Will do, @carver. Thanks. :)

**Pull request closed without merging**
