### PR TITLE
Reject str as a primitive in to_hex()

### PR DESCRIPTION
**Pull request by palash25**
Relates to #85

### What was wrong?

`to_hex` function in `conversions.py` when called
with a `str` type as a `primitive` argument used to
call `to_hex` again by calling it with the `str` value
as `text` argument instead of rejecting it

### How was it fixed?

An exception was added in `to_hex()` if str
type is provided to primitive argument to 
raise a `TypeError`

### CODE REVIEW

**Comment by carver** [comment]
Thanks. We almost always would like tests to verify updates. Are you up for adding a quick test to check that the TypeError is raised (say with `pytest.raises(TypeError, match="Unsupported type: The primitive argument")`).

Did you get a chance to try this change against py-evm and web3.py?

**Comment by palash25** [comment]
@carver actually I made this PR late at night and then dozed off  :laughing: so I didn't get the time to add tests. I'll add them today for sure.

No I haven't tested it against py-evm and web3.py will try to do it today. :+1:

**Comment by palash25** [comment]
tests added @carver have a look.

**Comment by carver** [comment]
I just ran a test on py-evm core and scanned through web3.py -- no problems identified. Thanks @palash25

**Pull request merged**
