### PR TITLE
Update eth_typing to 2.0.0

### PR DESCRIPTION
**Pull request by cburgdorf**
### What was wrong?

Needs upgrade to eth_typing 2.0.0

### How was it fixed?

Upgraded

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by carver** [comment]
Hm, yeah, I suppose if this is going to break builds like py-evm, then the responsible thing is to do a major version bump on eth-utils so that we don't break all new inbound PRs. I'm okay with it, and (especially with libraries) I think we can start to be conservative, and bump major versions whenever we suspect a backwards incompatibility.

In this one special case... (I hate starting a line of thought that way), maybe it would be okay to just constrain py-evm to use eth-utils `<=v1.2.1` until we get it sorted. I don't think any other projects are using eth-typing, so it probably won't cause any serious trouble to just do a minor point release on eth-utils.

**Comment by cburgdorf** [comment]
>I don't think any other projects are using eth-typing

Yes, you're right. I think `eth-pm` used to use it but recently removed it when there was some pypy resolving trouble.

So, my vote is to merge this now and cut a point release so that we can move on with https://github.com/ethereum/py-evm/pull/1293 soon before more type errors spread.

However, imho we should plan for `eth-utils` to do the following things soon:

1. add more type hints (there are a couple of open PRs that we probably need to polish). For instance, currently everything that we add an `@to_tuple` decorator does entirely lose type safety. In fact, there's a`mypy` flag `--disallow-untyped-decorators` that would disallow the usage of these decorators as they stand.

2. Enable PEP561 for `eth-utils`. This does mean that any project that uses `eth-utils` and also uses `mypy` will automatically pickup the types right from the `eth_utils` source code.

I'm happy to take care of this but I'd appreciate if we can merge this PR first and make a patch release to just focus on the `eth_typing` issue for now. Does that sound alright?

**Comment by pipermerriam** [comment]
@cburgdorf make it so.  I think the major version bump is my preferred way to go.  I suspect if we don't there will be unexpected breakages. At this point people are using are libraries, event the low level ones more and more.

**Comment by cburgdorf** [comment]
>make it so

Can you give me `pypy` superpowers for `eth-utils`

>I think the major version bump is my preferred way to go

If we do the `PEP561` stuff soon after we would have two major version bumps in a row soon. Alternatively I can try to fix everything at once and then do a major version bump.

**Comment by carver** [comment]
> If we do the PEP561 stuff soon after we would have two major version bumps in a row soon. Alternatively I can try to fix everything at once and then do a major version bump.

Or, we could release it as a v2-alpha, leaving room for the `PEP561` changes, before v2 turns beta.

**Comment by cburgdorf** [comment]
I think that's my preferred approach!

**Comment by pipermerriam** [comment]
:+1: to going ahead and PEP561-ing `eth-utils`

**Comment by cburgdorf** [comment]
Ok, merging this in now.

**Pull request merged**
