### PR TITLE
Adapte les fonctionnalités checksum à RSKIP60 et EIP55

### PR DESCRIPTION
**Pull request by Mesrinx**
Adapts checksum functionality to RSKIP60 and EIP55

## What was wrong?

Issue #

## How was it fixed?

Summary of approach.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/eth-utils/blob/master/newsfragments/README.md)

[//]: # (See: https://eth-utils.readthedocs.io/en/latest/contributing.html#pull-requests)
- [ ] Add entry to the [release notes](https://github.com/ethereum/eth-utils/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Review by pipermerriam — CHANGES_REQUESTED** [review]
We won't be including `chain_id` in `remove_0x_prefix`

If you would like this PR considered, please take the time to fill out the description in detail.

~~It's not clear to me what this PR is attempting to do...~~

After a small amount of searching this appears to implement https://eips.ethereum.org/EIPS/eip-2304

I think we're open to this functionality being included, however, you'll need to implement it differently as to not modify the `XXX_0x_prefix` function.

Also, this will require tests and documentation updates.  Please ping me when you're ready for me to take another look.

**Review by Mesrinx — COMMENTED** [review]
a corriger ?

**Review by Mesrinx — COMMENTED** [review]
merciii

**Review by Mesrinx — COMMENTED** [review]
?

**Pull request closed without merging**
