### PR TITLE
Join to template

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

The project template didn't have a shared history

### How was it fixed?

Merged the project with the template, and filled the template variables. A couple minor cleanups along the way.
### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/eth-utils/blob/master/newsfragments/README.md)

- [x] Add entry to the [release notes](https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by carver** [comment]
Oops, meant to mark this as a draft

**Comment by carver** [comment]
I could fix the lint errors by changing mypy.ini to `warn_return_any = False`. I'll see how long it takes to fix it up properly.

**Comment by carver** [comment]
Interesting, pydocstyle and black have conflicting opinions about how to format: black requires an extra newline after the docstring, and pydocstyle forbids it.

**Comment by pipermerriam** [comment]
It seems like pydocstyle has support for ignoring certain error codes:

http://www.pydocstyle.org/en/4.0.0/error_codes.html

**Comment by carver** [comment]
> It seems like pydocstyle has support for ignoring certain error codes:
> 
> http://www.pydocstyle.org/en/4.0.0/error_codes.html

Yup! But I think the pydocstyle upgrade is the smoother path. Here for more: https://github.com/ethereum/ethereum-python-project-template/issues/52

**Comment by carver** [comment]
I'm fine if you want to give a rubber stamp @pipermerriam -- I looked it over fairly carefully.

**Comment by pipermerriam** [comment]
Consider it rubber stamped.

**Review by pipermerriam — APPROVED** [review]
rubber stamped

**Pull request merged**
