### PR TITLE
try conditional cytoolz or toolz install based on python implementation

### PR DESCRIPTION
**Pull request by pipermerriam**
STUB

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by pipermerriam** [comment]
@carver this is really weird and I don't quite understand it (will actually dig into it tomorrow).

https://circleci.com/gh/ethereum/eth-utils/140?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Any idea why?

**Comment by pipermerriam** [comment]
extra weird: 37227bb breaks cpython and fixes pypy.  MADNESS!!!

**Comment by carver** [comment]
Something about the way `compose` works in the two libraries is different. Checking...

**Comment by carver** [comment]
In toolz:

```
>>> print(num_required_args(sorted_return))
0
```

In cytoolz:
```
>>> print(num_required_args(sorted_return))
None
```

**Comment by carver** [comment]
`None` is always valid, since it just means the library couldn't determine the right answer.

0 is clearly wrong here, based on our intention, but *technically* it's correct that the `Compose` object accepts a call without arguments, since it's `__call__` is defined with `(*args, **kwargs)`.

**Comment by carver** [comment]
Opened https://github.com/pytoolz/toolz/issues/396 which includes a workaround to add to the test file that checks if the methods are curriable.

**Comment by pipermerriam** [comment]
Given what appears to be a fundamental incompatibility of cytoolz and pypy, I think we may find ourselves looking for a different approach as this is kind of hairy and seems fragile.  Dunno.  thoughts?

**Comment by carver** [comment]
Depends on how much we think we can rely on compatibility between toolz and cytoolz. I would expect pretty close matching, so I think this approach is reasonable (just patching the one incompatibility between toolz and cytoolz).

**Comment by carver** [comment]
Hm, I'm confused why be42528 is necessary. I want to play around with it for a sec.

**Comment by carver** [comment]
blergh, `has_keywords` has the same problem.

```py
def enhanced_has_keywords(func):
    if isinstance(func, Compose):
        return enhanced_has_keywords(func.first)
    else:
        return has_keywords(func)
```

That saves us from having to special-case with be42528, and passes in my local pypy tests.

**Comment by pipermerriam** [comment]
Sorry for my lazyness 😔 thanks for finding the fix.

**Comment by pipermerriam** [comment]
Lets let this play out for a week or two and if nothing shits the bed we can propogate this across our other libraries.

**Pull request merged**
