### PR TITLE
Include tests in dist

### PR DESCRIPTION
**Pull request by njgheorghita**
### What was wrong?
#130 

@jluttine Can you confirm that this solution would be suitable for your use case? And then i'll make the same change to `eth-typing`

### How was it fixed?
Added tests to distribution according to solution found [here](https://stackoverflow.com/questions/32390705/should-i-include-tests-and-pyc-files-when-building-package-with-setuptools)

#### Cute Animal Picture
image

### CODE REVIEW

**Comment by njgheorghita** [comment]
@jluttine thanks!

**Comment by carver** [comment]
We should wait to merge this until deciding whether to include the tests in the distribution. I'm slightly against right now, because the tests often don't run out of the box, they usually need some environment setup first, via `tox`.

**Comment by pipermerriam** [comment]
@carver good additional point.  I'm also leaning towards :-1:

**Comment by njgheorghita** [comment]
Seems like this issue is good to be closed?

**Pull request closed without merging**
